# Stage 1
FROM node:16-alpine AS builder
WORKDIR /app
ENV BUILDDDD=1
COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY . .

RUN yarn lint && yarn test:ci && yarn build

# Stage 2
FROM nginx:1.21.0-alpine as production
ENV NODE_ENV=production

COPY --from=builder /app/build /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]